/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package celestialexpressions

import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
    }
}
